version: '2'
services:
    jhipstersoapsample-app:
        image: jhipstersoapsample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@jhipstersoapsample-oracle:1521:jhipsterSoapSample
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
